Each: fix example in comment
elliotchance/pie pull request #157
Opened 2020-02-02 09:55 UTC by AlessandroLorenzi

Using the example 
```
	myCars.Each(func(car *Car) {
		fmt.Printf("Car color is: %s\n", car.Color)
	})
```

I get the error:
```
./main.go:31:18: cannot use func literal (type func(*Car)) as type func(Car) in argument to myCars.Each
```

2020-10-02 15:46 UTC, AlessandroLorenzi commented
@elliotchance  pipeline fails because of the old versions of go

You should merge pr #163 before

```
$ go test -race ./pie -coverprofile=coverage.txt -covermode=atomic
# github.com/stretchr/testify/assert
../../stretchr/testify/assert/assertions.go:1703:5: undefined: errors.Is
../../stretchr/testify/assert/assertions.go:1726:6: undefined: errors.Is
../../stretchr/testify/assert/assertions.go:1749:5: undefined: errors.As
../../stretchr/testify/assert/assertions.go:1766:7: undefined: errors.Unwrap
../../stretchr/testify/assert/assertions.go:1770:7: undefined: errors.Unwrap
```

2020-10-03 16:23 UTC, elliotchance requested changes
I don't understand the motivation for this change? The example uses a pointer so it can demonstrate that it's not safe.

2020-10-04 13:19 UTC, AlessandroLorenzi commented
You are right, the point of the second example is that you should pass a pointer to element to be modified.
I had considered only the first example! :)

The function generated by pue requires a "Car", not a "*Car".

Give a look to example returns errors https://play.golang.org/p/u6RTkrs9svi

We should remove the second part of the example and  create a new function "EachPointer" like that:
```go
func (ss SliceType) EachPointer(fn func(*ElementType)) SliceType
	for i := range ss {
		fn(&ss[i])
	}

	return ss
}
``` 

Here a complete example: https://play.golang.org/p/2tdtK7ih54n

2020-10-05 18:07 UTC, elliotchance commented
That's because you're using the wrong slice type. If the element is `*Car` then you can infer the slice type is `[]*Car`. Pie doesn't manipulate types. Here's the complete example: https://play.golang.org/p/dEeIjB1NlVH

2021-12-01 14:24 UTC, closed without merging