add `chunk` func
elliotchance/pie pull request #178
Opened 2022-06-23 11:08 UTC by Luoxin

2022-06-27 03:19 UTC, elliotchance commented
I'm happy to keep v1 on maintenance mode (forever), but any new functionality should only [go into v2](https://github.com/elliotchance/pie/tree/master/v2).

2022-06-28 02:45 UTC, Luoxin commented
I do some work in v2，but I prefer sdk of v1

2022-06-29 19:30 UTC, elliotchance requested changes

2022-06-29 19:30 UTC, elliotchance commented on v2/chunk.go
> +func Chunk[T any](ss []T, chunkSize int, callback func(ss []T) (stopped bool)) {
This function feels like it might be ultra specific to your use case. Do you have some examples you can provide?

2023-01-09 16:35 UTC, elliotchance commented
Closing in favor of #184

2023-01-09 16:35 UTC, closed without merging