add Chunk to v2
elliotchance/pie pull request #184
Opened 2023-01-04 06:24 UTC by Imatvoid

Chunk splits the input and returns multi slices whose length equals chunkLength, except for the last slice which may contain fewer elements.

ps: Chunk returns  [][]T, so it can not be contained by the chain which type is []T.

2023-01-04 14:08 UTC, elliotchance requested changes

2023-01-05 08:34 UTC, Imatvoid commented on v2/chunk.go
> +	if step == 0 {
if the input array is [1, 2, 3] and chunkLength is 4, here l is 3 and step is 0.
expect to get [ [1, 2, 3] ]

2023-01-08 02:35 UTC, Imatvoid commented on v2/chunk.go
> +	if step == 0 {
Are there any other questions that need to be answered? or maybe you think this func should not be merged for some reason.😸
@elliotchance

2023-01-09 16:33 UTC, elliotchance approved these changes

2023-01-09 16:34 UTC, merged