Add Remove function
elliotchance/pie pull request #194
Opened 2023-06-08 18:01 UTC by chocolacula

I believe checking index and bounds is better than keep it without the check and panicking with a bit weird errors.

2023-06-14 18:38 UTC, chocolacula commented
@elliotchance any thoughts?

2023-06-15 04:41 UTC, chocolacula commented
> I don't like the way it uses an output parameter. It should return a new slice not containing the element. Also, Delete a more common term used by languages when deleting something by it's key. And finally, are you sure this works with a single element? It looks like it would panic. 

Done. One element will be deleted correctly. Added a test for that case.

2023-06-15 12:50 UTC, elliotchance requested changes

2023-06-15 12:50 UTC, elliotchance commented on v2/delete.go
> +func Delete[T any](ss []T, idx int) []T {
This also needs to be registered against the chainable types: https://github.com/elliotchance/pie/blob/master/v2/of.go, https://github.com/elliotchance/pie/blob/master/v2/of_numeric.go and https://github.com/elliotchance/pie/blob/master/v2/of_ordered.go

2023-06-15 12:50 UTC, elliotchance commented on v2/delete.go
> +func Delete[T any](ss []T, idx int) []T {
It also makes sense to me to allow zero or more indexes:

```
.Delete(3, 4, 5)
.Delete(bunchOfIndexes...)
```

Although this is a little more complicated, so I'm happy for that to come later if needed.

2023-06-16 17:39 UTC, chocolacula commented
I tried a few approaches and chose the best one. I added a little benchmark:
```
BenchmarkDelete-8                   3372           355714 ns/op          8003676 B/op      3 allocs/op
BenchmarkDelete-8                   2890           357530 ns/op          8003675 B/op      3 allocs/op
BenchmarkDeleteShort-8          14604861           80.06 ns/op           176 B/op          3 allocs/op
BenchmarkDeleteShort-8          14294144           80.04 ns/op           176 B/op          3 allocs/op
BenchmarkDeleteSet-8                 184           6437496 ns/op         8003588 B/op      1 allocs/op
BenchmarkDeleteSet-8                 184           6431757 ns/op         8003589 B/op      1 allocs/op
BenchmarkDeleteSetShort-8        8599725           137.4 ns/op           128 B/op          1 allocs/op
BenchmarkDeleteSetShort-8        8649344           137.3 ns/op           128 B/op          1 allocs/op
```

You can find them in separate branch in [delete_test.go](https://github.com/chocolacula/pie/blob/delete_benchmarks/v2/delete_test.go)

2023-06-19 17:03 UTC, chocolacula commented
@elliotchance please review

2023-06-19 20:14 UTC, elliotchance approved these changes

2023-06-19 20:16 UTC, merged