added rotate
elliotchance/pie pull request #198
Opened 2023-09-07 01:11 UTC by SlothNinja

I had a need to treat a slice as a circular shift register. Rotate permits circular shifts (i.e., rotates) to left or right.

2023-09-07 13:47 UTC, elliotchance requested changes

2023-09-07 13:47 UTC, elliotchance commented on v2/rotate.go
> +func Rotate[T any](ss []T, n int) []T {
Please add this to all the Of types so it can also be chained: https://github.com/elliotchance/pie/pull/194/files

2023-09-07 22:27 UTC, SlothNinja commented
Still new to generating/updating pull requests. I added the requested feature to the rotate branch. Not sure what I need to do to update the pull request.

2023-09-08 17:37 UTC, elliotchance approved these changes

2023-09-08 17:38 UTC, merged